datashader 0.14.3
AnacondaRecipes/datashader-feedstock pull request #5
Opened 2022-12-07 10:29 UTC by skupr-anaconda

**Recipe directory diff between current master and this update:**
``` diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index a09a6a1..e1667b1 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,5 +1,5 @@
 {% set name = "datashader" %}
-{% set version = "0.14.2" %}
+{% set version = "0.14.3" %}
 
 package:
   name: {{ name|lower }}
@@ -7,7 +7,7 @@ package:
 
 source:
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datashader-{{ version }}.tar.gz
-  sha256: abc68ea6e243e9a5fd9bd8cf9bd3d8e6f6460492fa2697fea4f1db71054e24b8
+  sha256: cc76e8d372e5e341fca240486aaad64896f2e1a40083bba41133477ab50f5f6f
 
 build:
   number: 0

```

**Jira ticket:** [PKG-817
PKG-748
PKG-732](https://anaconda.atlassian.net/browse/PKG-817
https://anaconda.atlassian.net/browse/PKG-748
https://anaconda.atlassian.net/browse/PKG-732) (datashader
datashader
datashader-0.14.3
0.14.1
0.14.2)

**The upstream data:**
Github releases:  https://github.com/holoviz/datashader/releases
[Diff between the latest and previous upstream releases](https://github.com/holoviz/datashader/compare/0.14.2...0.14.3)
License: INFO: https://github.com/holoviz/datashader/blob/master/LICENSE.txt
Changelog: https://github.com/holoviz/datashader/blob/master/CHANGELOG.rst
Requirements:
 * setup.cfg:  https://github.com/holoviz/datashader/blob/v0.14.3/setup.cfg
 * setup.py:  https://github.com/holoviz/datashader/blob/v0.14.3/setup.py
 *  pyproject.toml:  https://github.com/holoviz/datashader/blob/v0.14.3/pyproject.toml

**_Actions:_**

1. 

**_Notes:_**
 * 

**Package's statistics**
<details>

 * Priority B | effort: easy | Category: anaconda_affiliated | subcategory:  | pkg_type: python
 * Outdated platfroms: 'linux-64', 'linux-aarch64', 'linux-ppc64le', 'osx-64', 'osx-arm64', 'win-64'
 * Latest version: 0.14.3
 * Release on PyPi:
    * version: 0.14.3
    * date: 2022-11-17T15:30:05
* [PyPi history](https://pypi.org/project/datashader/#history)
 * Popularity: 
    * 3 months downloads: 377201.0
    * All time:  444792 downloads -  datashader  0.14.3  Data visualization toolchain based on aggregating into a grid  

</details>

**Other checks:**

<details>

1. - [x] https://github.com/holoviz/datashader/tree/v0.14.3 exists
2. - [x] https://datashader.org is present
3. - [ ] Check the pinnings
4. - [x] https://github.com/holoviz/datashader/blob/master/CHANGELOG.rst exists
5. - [ ] Additional research
    https://github.com/holoviz/datashader/issues
    200
6. - [x] `dev_url` is present
    https://github.com/holoviz/datashader
7. - [x] `doc_url` is present
    https://datashader.org
8. - [ ] Verify that the `build_number` is correct
9. - [x] has `setuptools`
10. - [x] has `wheel`
11. - [ ] NO `pip` in test
    pip
pip
12. - [ ] Verify the test section
13. - [ ] Verify if the package is `architecture specific`
14. - [ ] Verify that private modules are not mentioned in the recipe For example: (_private_module)
15.  - [x] license_file: LICENSE.txt is present
16. - [x] License: BSD-3-Clause
    - [ ] License is `spdx` compliant
 * Check if the license identifier has correct name from the SPDX License List

| Identifier                           |
|:-------------------------------------|
| BSD-3-Clause                         |
| BSD-3-Clause-Attribution             |
| BSD-3-Clause-Clear                   |
| BSD-3-Clause-LBNL                    |
| BSD-3-Clause-Modification            |
| BSD-3-Clause-No-Military-License     |
| BSD-3-Clause-No-Nuclear-License      |
| BSD-3-Clause-No-Nuclear-License-2014 |
| BSD-3-Clause-No-Nuclear-Warranty     |
| BSD-3-Clause-Open-MPI                |

17. - [x] license_family BSD is present
</details>

**Check dependency issues:**

<details>
../aggregate/datashader-feedstock/recipe/meta.yaml
Dependencies: ['param >=1.6.1', 'colorcet >=0.9.0', 'python', 'dask-core', 'xarray >=0.9.6', 'setuptools', 'requests', 'pip', 'pyct', 'numba >=0.51', 'pyct >=0.4.5', 'pandas >=0.24.1', 'pillow >=3.1.1', 'scipy', 'datashape >=0.5.1', 'param', 'wheel']

noarch:
- py3.7: No issues found
- py3.8: No issues found
- py3.9: No issues found
- py3.10: No issues found

linux-64:
- py3.7: No issues found
- py3.8: No issues found
- py3.9: No issues found
- py3.10: Encountered problems while solving:
  - nothing provides __glibc >=2.17 needed by libgcc-ng-11.2.0-h1234567_0

linux-ppc64le:
- py3.7: No issues found
- py3.8: No issues found
- py3.9: No issues found
- py3.10: No issues found

linux-s390x:
- py3.7: The following packages are missing from the target environment:
  - datashape >=0.5.1

- py3.8: The following packages are missing from the target environment:
  - datashape >=0.5.1

- py3.9: The following packages are missing from the target environment:
  - datashape >=0.5.1

- py3.10: The following packages are missing from the target environment:
  - numba >=0.51

osx-64:
- py3.7: No issues found
- py3.8: No issues found
- py3.9: No issues found
- py3.10: No issues found

osx-arm64:
- py3.8: No issues found
- py3.9: No issues found
- py3.10: No issues found

win-64:
- py3.7: No issues found
- py3.8: No issues found
- py3.9: No issues found
- py3.10: No issues found

</details>

**Links:**
* [Anaconda Recipes feedstock](https://github.com/AnacondaRecipes/datashader-feedstock)
* [Update branch](https://github.com/AnacondaRecipes/datashader-feedstock/tree/0.14.3)
* [conda-forge recipe](https://github.com/{upstream}/{feedstock_name}-feedstock)
* [PyPI](https://pypi.org/project/datashader)
* [Diff between upstream and feature branch](https://github.com/conda-forge/datashader-feedstock/compare/main...AnacondaRecipes:0.14.3)
* [Diff between origin and feature branch](https://github.com/AnacondaRecipes/datashader-feedstock/compare/master...AnacondaRecipes:0.14.3)
* [The last merged PRs](https://github.com/AnacondaRecipes/datashader-feedstock/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc+)

**Updating the recipe:**
If the recipe needs additional modification the update branch can be modified. Note that the PR diffs are not updated with these changes.
```
git clone -b 0.14.3 git@github.com:AnacondaRecipes/datashader-feedstock.git
```

2022-12-07 10:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_584okig_7h/clone/recipe/meta.yaml:73: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_584okig_7h/clone/recipe/meta.yaml:73: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-08 09:11 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_2f_6xgi7_s/clone/recipe/meta.yaml:80: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_2f_6xgi7_s/clone/recipe/meta.yaml:80: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-08 09:24 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_97h2zi33lo/clone/recipe/meta.yaml:76: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_97h2zi33lo/clone/recipe/meta.yaml:76: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-12-08 10:19 UTC, katietz requested changes

2022-12-08 10:19 UTC, katietz commented on recipe/meta.yaml
> -    - datashape >=0.5.1
why we remove all those version constrains here?

2022-12-08 10:19 UTC, katietz commented on recipe/meta.yaml
> +    - numpy
this looks not right, as it is just pinned to the random version from cbc.  it hould be something >=....,<2 ...

2022-12-08 10:47 UTC, skupr-anaconda commented on recipe/meta.yaml
> -    - datashape >=0.5.1
They were removed by the maintainers https://github.com/holoviz/datashader/blob/v0.14.3/setup.py#L11-L24

2022-12-08 10:52 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - numpy
I've pinned `numpy >=1.19,<2.0a`

2022-12-08 10:53 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_423ivcj_ih/clone/recipe/meta.yaml:76: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_423ivcj_ih/clone/recipe/meta.yaml:76: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-12-08 10:56 UTC, skupr-anaconda commented on recipe/meta.yaml
> -    - datashape >=0.5.1
This PR curated dependencies and made them without pinnings https://github.com/holoviz/datashader/pull/1116

2022-12-09 02:51 UTC, cbouss approved these changes
LGTM

2022-12-12 10:07 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_838qmnwz0j/clone/recipe/meta.yaml:76: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_838qmnwz0j/clone/recipe/meta.yaml:76: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-12-12 10:44 UTC, merged

2022-12-12 10:44 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_3aj0q9gjrz/clone/recipe/meta.yaml:76: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_3aj0q9gjrz/clone/recipe/meta.yaml:76: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>